Added core plugin structure
xmartlabs/BuildSlackNotifier pull request #1
Opened 2017-03-08 15:27 UTC by diegomedina248

Added core plugin structure

2017-03-08 15:38 UTC, bryant1410 requested changes
Left few comments. I avoided to make code style comments as this code won't be maintained a lot.

2017-03-08 15:38 UTC, bryant1410 commented on CHANGELOG.md
> +All notable changes to BuildSlackNotifier will be documented in this file.
This line should be removed

2017-03-08 15:38 UTC, bryant1410 commented on README.md
> +* [Diego Medina](https://github.com/xmartlabs)
Maybe link to your profile, not Xmartlabs'

2017-03-08 15:38 UTC, bryant1410 commented on README.md
> +If you use **BuildSlackNotifier** in your app We would love to hear about it! Drop us a line on [twitter](https://twitter.com/xmartlabs).
app We -> app, we

2017-03-08 15:38 UTC, bryant1410 commented on CONTRIBUTING.md
> +### Asking Questions
I think we should respect header levels, but who cares

2017-03-08 15:42 UTC, diegomedina248 commented on README.md
> +* [Diego Medina](https://github.com/xmartlabs)
yeah that's what I intended :)

2017-03-08 15:44 UTC, diegomedina248 commented
@bryant1410 if you saw any code style violation, please do comment it here. We should maintain the same standards throughout all of our projects

2017-03-08 15:46 UTC, bryant1410 commented
> @bryant1410 if you saw any code style violation, please do comment it here. We should maintain the same standards throughout all of our projects

You will regret for sure...

![evil](https://media2.giphy.com/media/yOdLsvql5Rxio/giphy.gif)

2017-03-08 15:54 UTC, bryant1410 requested changes

2017-03-08 15:54 UTC, bryant1410 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Additional Info:
Here too :smile:

2017-03-08 15:54 UTC, bryant1410 commented on CHANGELOG.md
> +### [1.0.0](https://github.com/xmartlabs/BuildSlackNotifier/releases/tag/1.0.0)
And here

2017-03-08 15:54 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +
space

2017-03-08 15:54 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/SlackURL.java
> +  String url;
Couldn't this be private?

2017-03-08 15:54 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/Attachment.java
> +  public AttachmentType color;
Couldn't all these be private?

2017-03-08 15:54 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/AttachmentField.java
> +  String title;
And these ones

2017-03-08 15:54 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/AttachmentField.java
> +public class AttachmentField {
Access can be weaker :smile: please see all Intellij warnings

2017-03-08 16:32 UTC, diegomedina248 commented
What a shame @bryant1410, you didn't use the `…` above

2017-03-08 17:35 UTC, bryant1410 approved these changes
Have you tested with these changes? If not, could you do it?

2017-03-08 23:30 UTC, mirland requested changes

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +  private List<SlackURL> urls = new ArrayList<>();
it should be `final`

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +  public BuildSlackNotifier(ArrayList<SlackURL> urls) {
should be `nonNull`

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +        sendNotificationToSlack(build, listener, url.getUrl());
in my opinion the try/catch should be in inside the `for`

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +    public boolean configure(StaplerRequest req, JSONObject formData) throws FormException {
I think that `request` is better than `req`

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/SlackURL.java
> +  public void setUrl(String url) {
is it necessary? shouldn't be `final` ?

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/helper/GsonHelper.java
> +  static {
remove the static, use inline

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/helper/ResultHelper.java
> +    return "The build completed with some errors, but it wasn't marked as failed";
add the result in the result

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/Request.java
> +  private List<Attachment> attachments;
final

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/Request.java
> +public class Request {
final

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/request/Attachment.java
> +public class Attachment {
final

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/helper/GsonHelper.java
> +public class GsonHelper {
final

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/SlackURL.java
> +public class SlackURL {
final

2017-03-08 23:30 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +public class BuildSlackNotifier extends Recorder {
final

2017-03-10 14:07 UTC, diegomedina248 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/helper/ResultHelper.java
> +    return "The build completed with some errors, but it wasn't marked as failed";
That's done through the attachment type

2017-03-10 14:10 UTC, diegomedina248 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +  public BuildSlackNotifier(ArrayList<SlackURL> urls) {
Can't. For some reason it breaks the plugin (guessing something that Jenkins doesn't like)

2017-03-10 14:29 UTC, diegomedina248 commented
@bryant1410 I've tested it with these latests changes and seems to be working.

2017-03-10 17:19 UTC, mirland approved these changes

2017-03-10 17:19 UTC, matir91 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +          sendNotificationToSlack(build, listener, url.getUrl());
indentation

2017-03-10 17:41 UTC, diegomedina248 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +          sendNotificationToSlack(build, listener, url.getUrl());
shouldn't it be indented with 2 spaces?

2017-03-10 17:41 UTC, bryant1410 commented on src/main/java/com/xmartlabs/jenkins/buildslacknotifier/BuildSlackNotifier.java
> +          sendNotificationToSlack(build, listener, url.getUrl());
I'm counting 3 here

2017-03-10 19:30 UTC, michaelEllisUy approved these changes

2017-03-10 19:32 UTC, merged